tasks:
  - name: "runserver"
    init: |
      gp sync-await prebuild
    command:
      poetry run python manage.py runserver
  - name: "console"
    init: |
      if [ ! -f pyproject.toml ]; then
      poetry init -n
      poetry add django
      poetry run django-admin startproject config .
      sed -i "s/ALLOWED_HOSTS = \[\]/ALLOWED_HOSTS = \[\"localhost\"\]\nCSRF_TRUSTED_ORIGINS = \[\"https:\/\/*.ws-us72.gitpod.io\"\]/g" config/settings.py
      sed -i "s/UTC/Asia\/Seoul/g" config/settings.py
      else
      poetry update
      fi
      if [ ! -s db.sqlite3 ]; then
      poetry run python manage.py migrate
      clear && echo "Create Admin account:"
      poetry run python manage.py createsuperuser
      fi
    command: |
      gp sync-done prebuild
      clear && gp ports await 8000
      gp preview $(gp url 8000) --external
ports:
  - port: 8000
    visibility: private
    onOpen: notify

vscode:
  extensions:
    - ms-python.python